import { GameSong } from './types';

export interface PresetTasteProfile {
  id: string;
  name: string;
  avatar: string;
  genre: string;
  description: string;
  tracks: Array<{ title: string; artist: string; album?: string; year?: number }>;
}

export const PRESET_TASTE_PROFILES: PresetTasteProfile[] = [
  {
    id: 'pop_superstar',
    name: 'Emma (Pop Enthusiast)',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
    genre: 'Global Pop & Chart-Toppers',
    description: 'Lives on Billboard Hot 100, Taylor Swift, Dua Lipa, and Harry Styles.',
    tracks: [
      { title: 'Cruel Summer', artist: 'Taylor Swift', year: 2019 },
      { title: 'Levitating', artist: 'Dua Lipa', year: 2020 },
      { title: 'As It Was', artist: 'Harry Styles', year: 2022 },
      { title: 'Anti-Hero', artist: 'Taylor Swift', year: 2022 },
      { title: 'Blinding Lights', artist: 'The Weeknd', year: 2019 },
      { title: 'Flowers', artist: 'Miley Cyrus', year: 2023 },
      { title: 'Espresso', artist: 'Sabrina Carpenter', year: 2024 },
      { title: 'Vampire', artist: 'Olivia Rodrigo', year: 2023 },
      { title: 'Good 4 U', artist: 'Olivia Rodrigo', year: 2021 },
      { title: 'Shape of You', artist: 'Ed Sheeran', year: 2017 },
      { title: 'Greedy', artist: 'Tate McRae', year: 2023 },
      { title: 'Dance The Night', artist: 'Dua Lipa', year: 2023 },
      { title: 'Watermelon Sugar', artist: 'Harry Styles', year: 2019 },
      { title: 'Bad Guy', artist: 'Billie Eilish', year: 2019 },
      { title: 'Birds of a Feather', artist: 'Billie Eilish', year: 2024 },
      { title: 'Starboy', artist: 'The Weeknd', year: 2016 },
      { title: 'Karma', artist: 'Taylor Swift', year: 2022 },
      { title: 'Please Please Please', artist: 'Sabrina Carpenter', year: 2024 },
      { title: 'Don\'t Start Now', artist: 'Dua Lipa', year: 2019 },
      { title: 'Houdini', artist: 'Dua Lipa', year: 2023 },
      { title: 'Stay', artist: 'The Kid LAROI, Justin Bieber', year: 2021 },
      { title: 'Peaches', artist: 'Justin Bieber', year: 2021 },
      { title: 'Save Your Tears', artist: 'The Weeknd', year: 2020 },
      { title: 'Positions', artist: 'Ariana Grande', year: 2020 },
      { title: 'We Can\'t Be Friends', artist: 'Ariana Grande', year: 2024 },
      { title: 'Unholy', artist: 'Sam Smith, Kim Petras', year: 2022 },
      { title: 'About Damn Time', artist: 'Lizzo', year: 2022 },
      { title: '7 rings', artist: 'Ariana Grande', year: 2019 },
      { title: 'Lover', artist: 'Taylor Swift', year: 2019 },
      { title: 'Golden', artist: 'Harry Styles', year: 2019 }
    ]
  },
  {
    id: 'hiphop_head',
    name: 'Marcus (Hip-Hop & R&B)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop',
    genre: 'Hip-Hop & Trap & R&B',
    description: 'Kendrick Lamar, Drake, Travis Scott, and SZA on repeat.',
    tracks: [
      { title: 'Not Like Us', artist: 'Kendrick Lamar', year: 2024 },
      { title: 'FE!N', artist: 'Travis Scott', year: 2023 },
      { title: 'Snooze', artist: 'SZA', year: 2022 },
      { title: 'God\'s Plan', artist: 'Drake', year: 2018 },
      { title: 'HUMBLE.', artist: 'Kendrick Lamar', year: 2017 },
      { title: 'Sicko Mode', artist: 'Travis Scott', year: 2018 },
      { title: 'Kill Bill', artist: 'SZA', year: 2022 },
      { title: 'First Person Shooter', artist: 'Drake, J. Cole', year: 2023 },
      { title: 'Goosebumps', artist: 'Travis Scott', year: 2016 },
      { title: 'Money Trees', artist: 'Kendrick Lamar', year: 2012 },
      { title: 'No Role Modelz', artist: 'J. Cole', year: 2014 },
      { title: 'Rich Flex', artist: 'Drake, 21 Savage', year: 2022 },
      { title: 'All The Stars', artist: 'Kendrick Lamar, SZA', year: 2018 },
      { title: 'Passionfruit', artist: 'Drake', year: 2017 },
      { title: 'My Eyes', artist: 'Travis Scott', year: 2023 },
      { title: 'Redrum', artist: '21 Savage', year: 2024 },
      { title: 'Like That', artist: 'Future, Metro Boomin, Kendrick Lamar', year: 2024 },
      { title: 'Type Shit', artist: 'Future, Metro Boomin, Travis Scott', year: 2024 },
      { title: 'Low Life', artist: 'Future, The Weeknd', year: 2016 },
      { title: 'Sunflower', artist: 'Post Malone, Swae Lee', year: 2018 },
      { title: 'Rockstar', artist: 'Post Malone', year: 2017 },
      { title: 'Hotline Bling', artist: 'Drake', year: 2015 },
      { title: 'DNA.', artist: 'Kendrick Lamar', year: 2017 },
      { title: 'Telekinesis', artist: 'Travis Scott, SZA', year: 2023 },
      { title: 'Lovin On Me', artist: 'Jack Harlow', year: 2023 },
      { title: 'What\'s Poppin', artist: 'Jack Harlow', year: 2020 },
      { title: 'Carnival', artist: '¥$, Kanye West, Ty Dolla $ign', year: 2024 },
      { title: 'Flashing Lights', artist: 'Kanye West', year: 2007 },
      { title: 'Stronger', artist: 'Kanye West', year: 2007 },
      { title: 'Swimming Pools', artist: 'Kendrick Lamar', year: 2012 }
    ]
  },
  {
    id: 'desi_vibes',
    name: 'Aarav (Bollywood & Desi)',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop',
    genre: 'Bollywood & Punjabi & Indie Desi',
    description: 'Arijit Singh, AP Dhillon, Pritam, Diljit Dosanjh & soulful melodies.',
    tracks: [
      { title: 'Kesariya', artist: 'Arijit Singh, Pritam', year: 2022 },
      { title: 'Tum Hi Ho', artist: 'Arijit Singh', year: 2013 },
      { title: 'Excuses', artist: 'AP Dhillon, Gurinder Gill', year: 2021 },
      { title: 'Apna Bana Le', artist: 'Arijit Singh, Sachin-Jigar', year: 2022 },
      { title: 'Tauba Tauba', artist: 'Karan Aujla', year: 2024 },
      { title: 'Choo Lo', artist: 'The Local Train', year: 2015 },
      { title: 'Lover', artist: 'Diljit Dosanjh', year: 2021 },
      { title: 'Tere Vaaste', artist: 'Varun Jain, Sachin-Jigar', year: 2023 },
      { title: 'Channa Mereya', artist: 'Arijit Singh, Pritam', year: 2016 },
      { title: 'Kal Ho Naa Ho', artist: 'Sonu Nigam, Shankar-Ehsaan-Loy', year: 2003 },
      { title: 'Kun Faya Kun', artist: 'A.R. Rahman, Javed Ali', year: 2011 },
      { title: 'Agar Tum Saath Ho', artist: 'Alka Yagnik, Arijit Singh', year: 2015 },
      { title: 'Softly', artist: 'Karan Aujla', year: 2023 },
      { title: 'Brown Munde', artist: 'AP Dhillon, Gurinder Gill', year: 2020 },
      { title: 'Tum Se Hi', artist: 'Mohit Chauhan, Pritam', year: 2007 },
      { title: 'Chaand Baaliyan', artist: 'Aditya A', year: 2020 },
      { title: 'Husn', artist: 'Anuv Jain', year: 2023 },
      { title: 'Baarishein', artist: 'Anuv Jain', year: 2018 },
      { title: 'Pehle Bhi Main', artist: 'Vishal Mishra, Raj Shekhar', year: 2023 },
      { title: 'Satranga', artist: 'Arijit Singh, Shreyas Puranik', year: 2023 },
      { title: 'Ilahi', artist: 'Arijit Singh, Pritam', year: 2013 },
      { title: 'Kabira', artist: 'Tochi Raina, Rekha Bhardwaj', year: 2013 },
      { title: 'Naina Da Kya Kasoor', artist: 'Amit Trivedi', year: 2018 },
      { title: 'G.O.A.T.', artist: 'Diljit Dosanjh', year: 2020 },
      { title: 'Winning Speech', artist: 'Karan Aujla', year: 2024 },
      { title: 'Ghungroo', artist: 'Arijit Singh, Shilpa Rao', year: 2019 },
      { title: 'Raataan Lambiyan', artist: 'Jubin Nautiyal, Asees Kaur', year: 2021 },
      { title: 'Shayad', artist: 'Arijit Singh, Pritam', year: 2020 },
      { title: 'Bulleya', artist: 'Amit Mishra, Pritam', year: 2016 },
      { title: 'Qaafirana', artist: 'Arijit Singh, Nikhita Gandhi', year: 2018 }
    ]
  },
  {
    id: 'indie_dreamer',
    name: 'Chloe (Indie & Alt-Rock)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
    genre: 'Indie Rock & Bedroom Pop',
    description: 'Arctic Monkeys, The 1975, Phoebe Bridgers, and Clairo.',
    tracks: [
      { title: 'Do I Wanna Know?', artist: 'Arctic Monkeys', year: 2013 },
      { title: 'Sweater Weather', artist: 'The Neighbourhood', year: 2013 },
      { title: '505', artist: 'Arctic Monkeys', year: 2007 },
      { title: 'Somebody Else', artist: 'The 1975', year: 2016 },
      { title: 'Sofia', artist: 'Clairo', year: 2019 },
      { title: 'Bags', artist: 'Clairo', year: 2019 },
      { title: 'Motion Sickness', artist: 'Phoebe Bridgers', year: 2017 },
      { title: 'Kyoto', artist: 'Phoebe Bridgers', year: 2020 },
      { title: 'Line Without a Hook', artist: 'Ricky Montgomery', year: 2016 },
      { title: 'Riptide', artist: 'Vance Joy', year: 2013 },
      { title: 'Tongue Tied', artist: 'GROUPLOVE', year: 2011 },
      { title: 'Electric Love', artist: 'BØRNS', year: 2015 },
      { title: 'Take a Walk', artist: 'Passion Pit', year: 2012 },
      { title: 'The Less I Know The Better', artist: 'Tame Impala', year: 2015 },
      { title: 'Borderline', artist: 'Tame Impala', year: 2020 },
      { title: 'Lost in Yesterday', artist: 'Tame Impala', year: 2020 },
      { title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', year: 2013 },
      { title: 'About You', artist: 'The 1975', year: 2022 },
      { title: 'Robbers', artist: 'The 1975', year: 2013 },
      { title: 'Heat Waves', artist: 'Glass Animals', year: 2020 },
      { title: 'Gooey', artist: 'Glass Animals', year: 2014 },
      { title: 'Young Folks', artist: 'Peter Bjorn and John', year: 2006 },
      { title: 'Cigarette Daydreams', artist: 'Cage The Elephant', year: 2013 },
      { title: 'Come a Little Closer', artist: 'Cage The Elephant', year: 2013 },
      { title: 'Midnight City', artist: 'M83', year: 2011 },
      { title: 'Wait', artist: 'M83', year: 2011 },
      { title: 'Little Dark Age', artist: 'MGMT', year: 2018 },
      { title: 'Kids', artist: 'MGMT', year: 2007 },
      { title: 'Electric Feel', artist: 'MGMT', year: 2007 },
      { title: 'Freaks', artist: 'Surf Curse', year: 2013 }
    ]
  },
  {
    id: 'rock_legend',
    name: 'David (Classic & Hard Rock)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
    genre: 'Classic Rock & 90s Grunge',
    description: 'Queen, Nirvana, AC/DC, Fleetwood Mac, and Guns N\' Roses.',
    tracks: [
      { title: 'Bohemian Rhapsody', artist: 'Queen', year: 1975 },
      { title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991 },
      { title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses', year: 1987 },
      { title: 'Hotel California', artist: 'Eagles', year: 1976 },
      { title: 'Back In Black', artist: 'AC/DC', year: 1980 },
      { title: 'Highway to Hell', artist: 'AC/DC', year: 1979 },
      { title: 'Dreams', artist: 'Fleetwood Mac', year: 1977 },
      { title: 'The Chain', artist: 'Fleetwood Mac', year: 1977 },
      { title: 'Come As You Are', artist: 'Nirvana', year: 1991 },
      { title: 'In The End', artist: 'Linkin Park', year: 2000 },
      { title: 'Numb', artist: 'Linkin Park', year: 2003 },
      { title: 'Don\'t Stop Me Now', artist: 'Queen', year: 1978 },
      { title: 'Another One Bites the Dust', artist: 'Queen', year: 1980 },
      { title: 'Livin\' On A Prayer', artist: 'Bon Jovi', year: 1986 },
      { title: 'You Give Love A Bad Name', artist: 'Bon Jovi', year: 1986 },
      { title: 'Enter Sandman', artist: 'Metallica', year: 1991 },
      { title: 'Nothing Else Matters', artist: 'Metallica', year: 1991 },
      { title: 'Stairway to Heaven', artist: 'Led Zeppelin', year: 1971 },
      { title: 'Whole Lotta Love', artist: 'Led Zeppelin', year: 1969 },
      { title: 'Smoke on the Water', artist: 'Deep Purple', year: 1972 },
      { title: 'Comfortably Numb', artist: 'Pink Floyd', year: 1979 },
      { title: 'Wish You Were Here', artist: 'Pink Floyd', year: 1975 },
      { title: 'Thunderstruck', artist: 'AC/DC', year: 1990 },
      { title: 'Paradise City', artist: 'Guns N\' Roses', year: 1987 },
      { title: 'Wonderwall', artist: 'Oasis', year: 1995 },
      { title: 'Don\'t Look Back In Anger', artist: 'Oasis', year: 1995 },
      { title: 'Californication', artist: 'Red Hot Chili Peppers', year: 1999 },
      { title: 'Under the Bridge', artist: 'Red Hot Chili Peppers', year: 1991 },
      { title: 'Seven Nation Army', artist: 'The White Stripes', year: 2003 },
      { title: 'Everlong', artist: 'Foo Fighters', year: 1997 }
    ]
  }
];

export function generateSongsFromProfile(profile: PresetTasteProfile, playerId: string): GameSong[] {
  return profile.tracks.map((t, idx) => ({
    id: `song_${profile.id}_${idx}`,
    title: t.title,
    artist: t.artist,
    year: t.year,
    album: t.album,
    audioUrl: '', // Will be resolved dynamically via iTunes resolver
    owners: [playerId]
  }));
}
